spring:
  config:
    import: optional:file:.env[.properties]
  profiles.include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#        show_sql: true

redis:
  host: ${REDIS_DEV_HOST}
  port: ${REDIS_DEV_PORT}
  nodes: ${REDIS_DEV_NODES[0]}, ${REDIS_DEV_NODES[1]}, ${REDIS_DEV_NODES[2]}, ${REDIS_DEV_NODES[3]}, ${REDIS_DEV_NODES[4]}, ${REDIS_DEV_NODES[5]}

jwt:
  bearer-type: ${BEARER_TYPE}
  secret: ${TOKEN_SECRET}
  access-token:
    expire-duration: ${ACCESS_TOKEN_EXPIRE_DURATION}
    cookie-name: ${ACCESS_TOKEN_NAME}
  refresh-token:
    expire-duration: ${REFRESH_TOKEN_EXPIRE_DURATION}
    cookie-name: ${REFRESH_TOKEN_NAME}
